INSERT INTO permissions (id, name, resource, action, scope, category, description) VALUES
-- Patient Administration
(gen_random_uuid(), 'patient:read', 'patient', 'read', 'own', 'patient_admin', 'View patient demographics'),
(gen_random_uuid(), 'patient:write', 'patient', 'write', 'department', 'patient_admin', 'Create/update patient demographics'),
(gen_random_uuid(), 'patient:delete', 'patient', 'delete', 'hospital', 'patient_admin', 'Delete/merge patient records'),
(gen_random_uuid(), 'patient:export', 'patient', 'export', 'organization', 'patient_admin', 'Export patient data'),
(gen_random_uuid(), 'encounter:read', 'encounter', 'read', 'own', 'patient_admin', 'View encounter details'),
(gen_random_uuid(), 'encounter:write', 'encounter', 'write', 'department', 'patient_admin', 'Create/update encounters'),
(gen_random_uuid(), 'encounter:close', 'encounter', 'close', 'department', 'patient_admin', 'Close/complete encounter'),
(gen_random_uuid(), 'admission:create', 'admission', 'create', 'hospital', 'patient_admin', 'Admit patient to inpatient'),
(gen_random_uuid(), 'admission:approve', 'admission', 'approve', 'hospital', 'patient_admin', 'Approve admission (insurance)'),
(gen_random_uuid(), 'transfer:write', 'transfer', 'write', 'hospital', 'patient_admin', 'Transfer patient between units'),
(gen_random_uuid(), 'discharge:write', 'discharge', 'write', 'department', 'patient_admin', 'Process discharge'),
(gen_random_uuid(), 'discharge:approve', 'discharge', 'approve', 'hospital', 'patient_admin', 'Approve discharge summary'),

-- Clinical Care
(gen_random_uuid(), 'clinical:read', 'clinical', 'read', 'own', 'clinical', 'View clinical records'),
(gen_random_uuid(), 'clinical:write', 'clinical', 'write', 'own', 'clinical', 'Document clinical notes'),
(gen_random_uuid(), 'clinical:sign', 'clinical', 'sign', 'own', 'clinical', 'Sign/attest clinical notes'),
(gen_random_uuid(), 'order:read', 'order', 'read', 'own', 'clinical', 'View orders'),
(gen_random_uuid(), 'order:write', 'order', 'write', 'own', 'clinical', 'Create orders (CPOE)'),
(gen_random_uuid(), 'order:approve', 'order', 'approve', 'hospital', 'clinical', 'Approve high-risk orders'),
(gen_random_uuid(), 'order:discontinue', 'order', 'discontinue', 'own', 'clinical', 'Discontinue orders'),
(gen_random_uuid(), 'medication:read', 'medication', 'read', 'own', 'clinical', 'View medication orders'),
(gen_random_uuid(), 'medication:administer', 'medication', 'administer', 'own', 'clinical', 'Administer medications'),
(gen_random_uuid(), 'medication:dispense', 'medication', 'dispense', 'department', 'clinical', 'Dispense medications'),
(gen_random_uuid(), 'diagnosis:write', 'diagnosis', 'write', 'own', 'clinical', 'Record diagnoses'),
(gen_random_uuid(), 'diagnosis:code', 'diagnosis', 'code', 'own', 'clinical', 'Assign ICD-10 codes'),
(gen_random_uuid(), 'procedure:write', 'procedure', 'write', 'own', 'clinical', 'Document procedures'),
(gen_random_uuid(), 'allergy:write', 'allergy', 'write', 'own', 'clinical', 'Record allergies'),
(gen_random_uuid(), 'vitals:read', 'vitals', 'read', 'own', 'clinical', 'View vital signs'),
(gen_random_uuid(), 'vitals:write', 'vitals', 'write', 'own', 'clinical', 'Record vital signs'),

-- Diagnostics
(gen_random_uuid(), 'lab:order', 'lab', 'order', 'own', 'diagnostics', 'Order lab tests'),
(gen_random_uuid(), 'lab:result:read', 'lab', 'result:read', 'own', 'diagnostics', 'View lab results'),
(gen_random_uuid(), 'lab:result:verify', 'lab', 'result:verify', 'department', 'diagnostics', 'Verify lab results'),
(gen_random_uuid(), 'lab:result:approve', 'lab', 'result:approve', 'hospital', 'diagnostics', 'Approve final lab results'),
(gen_random_uuid(), 'specimen:collect', 'specimen', 'collect', 'department', 'diagnostics', 'Collect specimens'),
(gen_random_uuid(), 'rad:order', 'rad', 'order', 'own', 'diagnostics', 'Order radiology studies'),
(gen_random_uuid(), 'rad:result:read', 'rad', 'result:read', 'own', 'diagnostics', 'View radiology reports'),
(gen_random_uuid(), 'rad:result:verify', 'rad', 'result:verify', 'department', 'diagnostics', 'Verify radiology findings'),
(gen_random_uuid(), 'rad:result:approve', 'rad', 'result:approve', 'hospital', 'diagnostics', 'Approve final radiology reports'),
(gen_random_uuid(), 'rad:interpret', 'rad', 'interpret', 'own', 'diagnostics', 'Interpret imaging'),
(gen_random_uuid(), 'blood:order', 'blood', 'order', 'own', 'diagnostics', 'Order blood products'),
(gen_random_uuid(), 'blood:issue', 'blood', 'issue', 'department', 'diagnostics', 'Issue blood products'),
(gen_random_uuid(), 'blood:transfuse', 'blood', 'transfuse', 'own', 'diagnostics', 'Administer transfusion'),

-- Inpatient Care
(gen_random_uuid(), 'ipd:read', 'ipd', 'read', 'own', 'inpatient', 'View inpatient records'),
(gen_random_uuid(), 'ipd:write', 'ipd', 'write', 'own', 'inpatient', 'Document inpatient care'),
(gen_random_uuid(), 'bed:assign', 'bed', 'assign', 'hospital', 'inpatient', 'Assign beds to patients'),
(gen_random_uuid(), 'bed:transfer', 'bed', 'transfer', 'hospital', 'inpatient', 'Transfer patients between beds'),
(gen_random_uuid(), 'bed:release', 'bed', 'release', 'hospital', 'inpatient', 'Release beds on discharge'),
(gen_random_uuid(), 'surgery:schedule', 'surgery', 'schedule', 'hospital', 'inpatient', 'Schedule surgical cases'),
(gen_random_uuid(), 'surgery:perform', 'surgery', 'perform', 'own', 'inpatient', 'Perform surgeries'),
(gen_random_uuid(), 'surgery:assist', 'surgery', 'assist', 'own', 'inpatient', 'Assist in surgeries'),
(gen_random_uuid(), 'anesthesia:administer', 'anesthesia', 'administer', 'own', 'inpatient', 'Administer anesthesia'),
(gen_random_uuid(), 'icu:admit', 'icu', 'admit', 'hospital', 'inpatient', 'Admit to ICU'),
(gen_random_uuid(), 'icu:manage', 'icu', 'manage', 'own', 'inpatient', 'Manage ICU care'),
(gen_random_uuid(), 'ventilator:manage', 'ventilator', 'manage', 'own', 'inpatient', 'Manage ventilator settings'),

-- Outpatient Care
(gen_random_uuid(), 'opd:read', 'opd', 'read', 'own', 'outpatient', 'View OPD records'),
(gen_random_uuid(), 'opd:write', 'opd', 'write', 'own', 'outpatient', 'Document OPD visits'),
(gen_random_uuid(), 'appointment:schedule', 'appointment', 'schedule', 'all', 'outpatient', 'Schedule appointments'),
(gen_random_uuid(), 'appointment:reschedule', 'appointment', 'reschedule', 'all', 'outpatient', 'Reschedule appointments'),
(gen_random_uuid(), 'appointment:cancel', 'appointment', 'cancel', 'all', 'outpatient', 'Cancel appointments'),
(gen_random_uuid(), 'appointment:approve', 'appointment', 'approve', 'department', 'outpatient', 'Approve special appointments'),
(gen_random_uuid(), 'telemedicine:conduct', 'telemedicine', 'conduct', 'own', 'outpatient', 'Conduct telemedicine visits'),
(gen_random_uuid(), 'checkin:process', 'checkin', 'process', 'department', 'outpatient', 'Process patient check-in'),

-- Emergency Care
(gen_random_uuid(), 'ed:read', 'ed', 'read', 'own', 'emergency', 'View ED records'),
(gen_random_uuid(), 'ed:write', 'ed', 'write', 'own', 'emergency', 'Document ED care'),
(gen_random_uuid(), 'triage:assess', 'triage', 'assess', 'own', 'emergency', 'Perform triage assessment'),
(gen_random_uuid(), 'triage:assign', 'triage', 'assign', 'own', 'emergency', 'Assign triage priority'),
(gen_random_uuid(), 'ed:disposition', 'ed', 'disposition', 'own', 'emergency', 'Decide ED disposition'),
(gen_random_uuid(), 'fasttrack:manage', 'fasttrack', 'manage', 'own', 'emergency', 'Manage fast-track cases'),

-- Financial
(gen_random_uuid(), 'billing:read', 'billing', 'read', 'own', 'financial', 'View billing records'),
(gen_random_uuid(), 'billing:write', 'billing', 'write', 'department', 'financial', 'Create/modify billing items'),
(gen_random_uuid(), 'billing:post', 'billing', 'post', 'department', 'financial', 'Post charges to account'),
(gen_random_uuid(), 'invoice:generate', 'invoice', 'generate', 'department', 'financial', 'Generate invoices'),
(gen_random_uuid(), 'invoice:adjust', 'invoice', 'adjust', 'hospital', 'financial', 'Adjust invoice amounts'),
(gen_random_uuid(), 'invoice:void', 'invoice', 'void', 'hospital', 'financial', 'Void invoices'),
(gen_random_uuid(), 'claim:create', 'claim', 'create', 'department', 'financial', 'Create insurance claims'),
(gen_random_uuid(), 'claim:submit', 'claim', 'submit', 'hospital', 'financial', 'Submit claims to payers'),
(gen_random_uuid(), 'claim:adjudicate', 'claim', 'adjudicate', 'organization', 'financial', 'Adjudicate claims'),
(gen_random_uuid(), 'payment:post', 'payment', 'post', 'department', 'financial', 'Post payments'),
(gen_random_uuid(), 'payment:refund', 'payment', 'refund', 'hospital', 'financial', 'Process refunds'),
(gen_random_uuid(), 'coverage:verify', 'coverage', 'verify', 'department', 'financial', 'Verify insurance coverage'),
(gen_random_uuid(), 'authorization:obtain', 'authorization', 'obtain', 'department', 'financial', 'Obtain pre-authorizations'),

-- Pharmacy
(gen_random_uuid(), 'pharmacy:read', 'pharmacy', 'read', 'own', 'pharmacy', 'View pharmacy orders'),
(gen_random_uuid(), 'pharmacy:verify', 'pharmacy', 'verify', 'department', 'pharmacy', 'Verify medication orders'),
(gen_random_uuid(), 'pharmacy:dispense', 'pharmacy', 'dispense', 'department', 'pharmacy', 'Dispense medications'),
(gen_random_uuid(), 'formulary:manage', 'formulary', 'manage', 'organization', 'pharmacy', 'Manage drug formulary'),
(gen_random_uuid(), 'interaction:check', 'interaction', 'check', 'own', 'pharmacy', 'Check drug interactions'),
(gen_random_uuid(), 'stock:manage', 'stock', 'manage', 'hospital', 'pharmacy', 'Manage pharmacy inventory'),
(gen_random_uuid(), 'controlled:dispense', 'controlled', 'dispense', 'hospital', 'pharmacy', 'Dispense controlled substances'),

-- Administration
(gen_random_uuid(), 'user:read', 'user', 'read', 'tenant', 'administration', 'View user accounts'),
(gen_random_uuid(), 'user:write', 'user', 'write', 'tenant', 'administration', 'Create/modify user accounts'),
(gen_random_uuid(), 'user:deactivate', 'user', 'deactivate', 'tenant', 'administration', 'Deactivate user accounts'),
(gen_random_uuid(), 'role:assign', 'role', 'assign', 'tenant', 'administration', 'Assign roles to users'),
(gen_random_uuid(), 'role:manage', 'role', 'manage', 'tenant', 'administration', 'Create/modify roles'),
(gen_random_uuid(), 'audit:read', 'audit', 'read', 'tenant', 'administration', 'View audit logs'),
(gen_random_uuid(), 'audit:export', 'audit', 'export', 'tenant', 'administration', 'Export audit logs'),
(gen_random_uuid(), 'config:read', 'config', 'read', 'tenant', 'administration', 'View system configuration'),
(gen_random_uuid(), 'config:write', 'config', 'write', 'tenant', 'administration', 'Modify system configuration'),
(gen_random_uuid(), 'facility:manage', 'facility', 'manage', 'organization', 'administration', 'Manage facility/department setup'),
(gen_random_uuid(), 'report:run', 'report', 'run', 'organization', 'administration', 'Run operational reports'),
(gen_random_uuid(), 'report:admin', 'report', 'admin', 'tenant', 'administration', 'Create/modify reports');