// Code generated by protoc-gen-go. DO NOT EDIT.
// Minimal stub for compilation purposes

package patientv1

import (
	"time"
)

// Message types
type Address struct {
	Street     string
	City       string
	State      string
	PostalCode string
	Country    string
}

type EmergencyContact struct {
	Name     string
	Relation string
	Phone    string
}

type Insurance struct {
	Provider        string
	PolicyNo        string
	Tpa             string
	MemberId        string
	SumInsured      int64
	PolicyValidTill string
	CorporateName   string
}

type Medication struct {
	Drug      string
	Dose      string
	Frequency string
	Notes     string
}

type VitalSigns struct {
	Bp         string
	Hr         int32
	Temp       float32
	Spo2       int32
	Rr         int32
	Weight     float32
	Height     int32
	Bmi        float32
	RecordedAt *time.Time
}

type Patient struct {
	Id               string
	TenantId         string
	Mrn              string
	Name             string
	Dob              string
	Gender           string
	BloodGroup       string
	Phone            string
	Email            string
	Address          *Address
	Abha             string
	AadhaarLastFour  string
	EmergencyContact *EmergencyContact
	Insurance        *Insurance
	HomeMedications  []*Medication
	Allergies        []string
	VitalSigns       *VitalSigns
	Status           string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	DeletedAt        *time.Time
	CreatedBy        string
	UpdatedBy        string
}

type CreatePatientRequest struct {
	TenantId         string
	Name             string
	Dob              string
	Gender           string
	BloodGroup       string
	Phone            string
	Email            string
	Address          *Address
	Abha             string
	AadhaarLastFour  string
	EmergencyContact *EmergencyContact
	Insurance        *Insurance
	HomeMedications  []*Medication
	Allergies        []string
}

type CreatePatientResponse struct {
	Patient *Patient
	Mrn     string
}

type GetPatientRequest struct {
	PatientId string
	TenantId  string
}

type GetPatientResponse struct {
	Patient *Patient
}

type SearchPatientsRequest struct {
	TenantId  string
	Mrn       string
	FirstName string
	LastName  string
	Phone     string
	Email     string
	Page      int32
	PageSize  int32
	Status    string
}

type SearchPatientsResponse struct {
	Patients []*Patient
	Total    int64
	Page     int32
	PageSize int32
}

type ListPatientsRequest struct {
	TenantId string
	Status   string
	Page     int32
	PageSize int32
	SortBy   string
	SortDir  string
}

type ListPatientsResponse struct {
	Patients []*Patient
	Total    int64
	Page     int32
	PageSize int32
}

type UpdatePatientRequest struct {
	PatientId        string
	TenantId         string
	Name             string
	Phone            string
	Email            string
	Address          *Address
	EmergencyContact *EmergencyContact
	Insurance        *Insurance
	HomeMedications  []*Medication
	Allergies        []string
	VitalSigns       *VitalSigns
	Status           string
	UpdatedBy        string
}

type UpdatePatientResponse struct {
	Patient *Patient
}

type ActivatePatientRequest struct {
	PatientId string
	TenantId  string
	UpdatedBy string
}

type ActivatePatientResponse struct {
	Patient *Patient
}

type HealthResponse struct {
	Status string
}
